# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('History_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Create_Date', models.DateTimeField()),
                ('Lords_Table', models.BooleanField(default=True)),
                ('Prayer_Meeting', models.BooleanField(default=True)),
                ('Morning_Revival', models.BooleanField(default=True)),
                ('Bible_Reading', models.BooleanField(default=True)),
                ('Small_Group', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('Member_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Member_Type', models.CharField(choices=[('1', 'Children'), ('2', 'Pre-Youth'), ('3', 'Campus'), ('4', 'Young-Working'), ('5', 'Full-time')], max_length=1)),
                ('Contact', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=255)),
                ('Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancehistory',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attandance.Members'),
        ),
    ]
