# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0002_auto_20160927_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userName', models.CharField(max_length=40, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=40)),
                ('lastName', models.CharField(blank=True, max_length=40)),
                ('tagLine', models.CharField(blank=True, max_length=140)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
