# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0003_auto_20161004_0818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('Create_Date',)},
        ),
    ]
