# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0004_auto_20161004_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Member_Type',
            field=models.CharField(choices=[('1', 'Children'), ('2', 'Pre-Youth'), ('3', 'Campus'), ('4', 'Young-Working'), ('5', 'Community'), ('6', 'Full-time')], max_length=1),
        ),
    ]
