# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0005_auto_20161007_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Password',
        ),
    ]
