# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0006_remove_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Contact',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='member',
            name='Email',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='member',
            name='Family_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Given_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='Other_Name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='attendancehistory',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttandanceHistorys', to='attandance.Member'),
        ),
    ]
