# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0007_auto_20161010_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('District_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Zone', models.CharField(choices=[('1', 'Zone1'), ('2', 'Zone2'), ('3', 'Zone3')], max_length=3)),
                ('Create_Date', models.DateTimeField()),
                ('Location', models.CharField(max_length=120)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AddField(
            model_name='member',
            name='District_ID',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='attandance.District'),
        ),
    ]
