# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0008_auto_20161010_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='Zone',
            field=models.CharField(choices=[('0', 'All'), ('1', 'Zone1'), ('2', 'Zone2'), ('3', 'Zone3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='District_ID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='attandance.District'),
        ),
    ]
