# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0009_auto_20161010_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='District_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
