# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0010_district_district_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='Location',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='district',
            name='PostCode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
