# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attandance', '0012_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 28, 8, 2, 14, 293818)),
        ),
        migrations.AlterField(
            model_name='district',
            name='District_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='district',
            name='PostCode',
            field=models.CharField(max_length=20),
        ),
    ]
